### ISSUE TITLE
Enhance the process AllocationAuto with allocation of prepayments

### ISSUE THREAD

**Issue by SusanneCalderon** [adempiere/adempiere#1370] opened 2017-10-12 14:18 UTC
This process can be used as a process in the workflow Process_Invoice in order to allocate a prepayment of an order with the newly generated invoice.

**Comment by e-Evolution** [comment] 2017-10-12 16:28
Hi Susanne @SusanneCalderon , can you more detail about the process that you want execute?

**Comment by SusanneCalderon** [comment] 2017-10-31 23:45
Hello, here is the method which es called at the end of complete().

```
private String allocatePrepayments()
	{
		if (!get_ValueAsBoolean("IsAllocateImmediate"))
			return "";
		if (getC_Order_ID() == 0)
			return "";
		if (getC_Order_ID() != 0 && getC_Order().getC_POS_ID() != 0)
			return "";
		BiFunction<BigDecimal, BigDecimal, BigDecimal> getMaxPayAmt     = (t1, t2)  -> {
			return t1.abs().compareTo(t2.abs()) <=0? t1:t2;
		};
		BiFunction<BigDecimal, BigDecimal, BigDecimal> getOverUnderAmt    = ( payamt,  openamt)  -> {
			return payamt.abs().compareTo(openamt.abs()) >=0? Env.ZERO:openamt.subtract(payamt);};

		BiFunction<BigDecimal, Boolean, BigDecimal> getAmtIsreceipt    = ( amt,  isReceipt)  -> {
			return isReceipt?amt:amt.negate();};

		String whereClause = "C_ORDER_ID=? and docstatus in ('CO','CL') and isallocated = 'N'";
		List<MPayment> prepayments = new Query(getCtx(), MPayment.Table_Name, whereClause, get_TrxName())
				.setParameters(getC_Order_ID())
				.list();
		BigDecimal openAmt = getOpenAmt();
		for (MPayment pay:prepayments)
		{
			MAllocationHdr alloc = new MAllocationHdr (Env.getCtx(), true,	//	manual
					getDateInvoiced()	, getC_Currency_ID(), Env.getContext(Env.getCtx(), "#AD_User_Name"),
					get_TrxName());
			alloc.setAD_Org_ID(getAD_Org_ID());
			alloc.saveEx();
			BigDecimal aLineAmount = getMaxPayAmt.apply(openAmt,pay.getPayAmt());
			BigDecimal overUnderAmt = getOverUnderAmt.apply(aLineAmount, openAmt);
			//	Allocation Line
			MAllocationLine aLine = new MAllocationLine (alloc, getAmtIsreceipt.apply(aLineAmount, isSOTrx()) ,
					Env.ZERO, Env.ZERO, getAmtIsreceipt.apply(overUnderAmt, isSOTrx()));
			aLine.setDocInfo(getC_BPartner_ID(), getC_Order_ID(), getC_Invoice_ID());
			aLine.setPaymentInfo(pay.getC_Payment_ID(), 0);
			aLine.saveEx();
			if (!alloc.processIt(DocAction.ACTION_Complete)) //@Trifon
				throw new AdempiereException("Cannot complete allocation: " + alloc.getProcessMsg()); //@Trifon
			alloc.saveEx();
			openAmt = openAmt.subtract(aLineAmount);
		}
		return "";
	}
```

**Comment by SusanneCalderon** [comment] 2018-01-29 02:55
The commit was tested for purchase and sales.
Scenario:
- Order for $2500
- Prepayment 1 for Order: $500
- Prepayment 2 for Order: $200
- Invoice for Order: $600

Result:

- Prepayment 1 consumed
- Prepayment 2: Open amount $100
- Invoice paid

**Comment by e-Evolution** [comment] 2018-02-09 19:41
Problem to try applying the scripts related #1570

13:35:52.806     MIssue.saveNew: [POSave_5e0c8504-1d32-4428-9db2-2b01aae4d0e9] - AD_Issue - AD_Issue_ID=1010781 [183]
13:35:52.806     PgConnection.setAutoCommit:   setAutoCommit = {0} (false) [183]
13:35:52.807     PgConnection.setTransactionIsolation:   setTransactionIsolation = {0} (READ COMMITTED) [183]
===========> MigrationFromXML.process: Loading Migration from XML failed. [183]
org.adempiere.exceptions.AdempiereException: Loading migration from /Users/e-Evolution/Develop/ADempiere/adempiere/migration/390lts-391/03690_1370_InvoiceAllocateInmediate.xml failed.
	at org.compiere.process.MigrationFromXML.lambda$loadFile$0(MigrationFromXML.java:168)
	at org.compiere.util.Trx.run(Trx.java:527)
	at org.compiere.util.Trx.run(Trx.java:495)
	at org.compiere.process.MigrationFromXML.loadFile(MigrationFromXML.java:141)
	at org.compiere.process.MigrationFromXML.loadXML(MigrationFromXML.java:107)
	at org.compiere.process.MigrationFromXML.doIt(MigrationFromXML.java:49)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:174)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:127)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:160)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:105)
	at org.compiere.apps.ProcessCtl.startProcess(ProcessCtl.java:623)
	at org.compiere.apps.ProcessCtl.run(ProcessCtl.java:372)
caused by: org.adempiere.exceptions.AdempiereException: Process failed during execution Error:  Migration 3690 - InvoiceAllocateInmediate - 3.9.1 (D) ; Step: 270; Type: AD. Application failed: org.adempiere.exceptions.AdempiereException: Migration 3690 - InvoiceAllocateInmediate - 3.9.1 (D) ; Step: 270; Type: AD. Step 270, Record 86715 was not found in table Column (101).
	at org.eevolution.service.dsl.ProcessBuilder.execute(ProcessBuilder.java:297)
	at org.compiere.process.MigrationFromXML.applyMigration(MigrationFromXML.java:181)
	at org.compiere.process.MigrationFromXML.lambda$loadFile$0(MigrationFromXML.java:163)
	at org.compiere.util.Trx.run(Trx.java:527)
	at org.compiere.util.Trx.run(Trx.java:495)
	at org.compiere.process.MigrationFromXML.loadFile(MigrationFromXML.java:141)
	at org.compiere.process.MigrationFromXML.loadXML(MigrationFromXML.java:107)
	at org.compiere.process.MigrationFromXML.doIt(MigrationFromXML.java:49)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:174)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:127)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:160)

**Comment by SusanneCalderon** [comment] 2018-03-13 14:55
We corrected the xml

**Comment by SusanneCalderon** [comment] 2018-03-13 14:56
Correction: The allocation must be omitted when the document which is completed is a reversal document.

**Comment by wdtz** [comment] 2018-06-08 21:42
**Test results:**

1. When making an invoice with the total quantities of the purchase order the result is successful (the assignment is made)
2. When making an invoice with the partial quantities of the purchase order the result is unsuccessful (The assignment is not made)

**Improvement:**

1. The Auto Flag Assignment should go in the type of document

**Comment by e-Evolution** [comment] 2018-06-08 22:44
Hi  @wdtz Watdiza, @SusanneCalderon  Susanne what would be the reason for this behavior to be the default, I am trying to imagine in what cases I do not require an automatic assignment and I do not really find any for this specific scenery.

On the other hand, this behavior can only happen if a payment has been made to a sales order as an advance and in turn, an invoice related to the sales order was generated.

Do you really consider that we require a flag,?

Is ok for me if this the standard behavior since all the variables are determined

**Comment by yamelsenih** [comment] 2018-06-09 00:00
Hi @e-Evolution is nice to have a flag on Document Type, here a type of invoice vendor can be auto allocated with prepayment of order but exist other invoices that must be review and generate withholding before allocate payment.

A example for a Invoilce of Service (No Apply Auto Allocation): 
Order: $ 3000
Prepay: $2800
Invoice: $ 3000
The automatic allocation no apply for it because withholding is not applied yet.

Withholding for service: $ 150
Withholding for Tax: $ 100

- The process is: 3000 (Invoice) - 150 (Withholding for service) - 100 (Withholding for Tax) = **$ 2750**
- To allocate prepay = 2750 (Invoice Open) - 2750 (Prepay without 50 over under payment) = **$ 0**
The open payment for new invoice is **$ 50**

Example of eat invoice: 
Order: $ 3000
Prepay: $2800
Invoice: $ 3000
The automatic allocation no apply for it because withholding is not applied yet.

**Don't have Withholding**

- The process is: 3000 (Invoice) - 2800 (Prepay) = **$ 200**
The open invoice is **$ 200**

The auto allocation is fine for it

**Closed** 2018-08-16 00:15 UTC
Labels: (AP) Account Payable, (AR) Account Receivable, 01 enhancement
