### ISSUE TITLE
Function productattribute(p_m_attributesetinstance_id) not working in postgres

### ISSUE THREAD

**Issue by iscapnet** [adempiere/adempiere#984] opened 2017-04-15 13:41 UTC
Postgres throws an error when executing this function as _select * from dempiere.productattribute(100)_

ERROR:  invalid type name "M_AttributeSetInstance.Lot%TYPE"
LINE 35:     v_Lot           M_AttributeSetInstance.Lot%TYPE;
                             ^
QUERY:  

/*************************************************************************
 * The contents of this file are subject to the Compiere License.  You may
 * obtain a copy of the License at    http://www.compiere.org/license.html 
 * Software is on an  "AS IS" basis,  WITHOUT WARRANTY OF ANY KIND, either 
 * express or implied. See the License for details. Code: Compiere ERP+CRM
 * Copyright (C) 1999-2001 Jorg Janke, ComPiere, Inc. All Rights Reserved.
 *
 * converted to postgreSQL by Karsten Thiemann (Schaeffer AG), 
 * kthiemann@adempiere.org
 * 
 * Format v_GuaranteeDate as date 
 *************************************************************************
 * Title: Return Instance Attribute Info
 * Description:
 *  
 * Test:
    SELECT ProductAttribute (M_AttributeSetInstance_ID) 
    FROM M_InOutLine WHERE M_AttributeSetInstance_ID > 0
    --
    SELECT p.Name
    FROM C_InvoiceLine il LEFT OUTER JOIN M_Product p ON (il.M_Product_ID=p.M_Product_ID);
    SELECT p.Name || ProductAttribute (il.M_AttributeSetInstance_ID) 
    FROM C_InvoiceLine il LEFT OUTER JOIN M_Product p ON (il.M_Product_ID=p.M_Product_ID);
    
 ************************************************************************/

	
DECLARE

    v_Name          VARCHAR(2000) := '';
    v_NameAdd       VARCHAR(2000) := '';
    --
    v_Lot           M_AttributeSetInstance.Lot%TYPE;
    v_LotStart      M_AttributeSet.LotCharSOverwrite%TYPE;
    v_LotEnd        M_AttributeSet.LotCharEOverwrite%TYPE;
    v_SerNo         M_AttributeSetInstance.SerNo%TYPE;
    v_SerNoStart    M_AttributeSet.SerNoCharSOverwrite%TYPE;
    v_SerNoEnd      M_AttributeSet.SerNoCharEOverwrite%TYPE;
    v_GuaranteeDate M_AttributeSetInstance.GuaranteeDate%TYPE;
    
    r   RECORD;
    --

BEGIN
    --  Get Product Attribute Set Instance
    IF (p_M_AttributeSetInstance_ID > 0) THEN
        SELECT asi.Lot, asi.SerNo, asi.GuaranteeDate,
            COALESCE(a.SerNoCharSOverwrite, '#'::CHAR(1)), COALESCE(a.SerNoCharEOverwrite, ''::CHAR(1)),
            COALESCE(a.LotCharSOverwrite, '�'::CHAR(1)), COALESCE(a.LotCharEOverwrite, '�'::CHAR(1))
          INTO v_Lot, v_SerNo, v_GuaranteeDate,
            v_SerNoStart, v_SerNoEnd, v_LotStart, v_LotEnd
        FROM M_AttributeSetInstance asi
          INNER JOIN M_AttributeSet a ON (asi.M_AttributeSet_ID=a.M_AttributeSet_ID)
        WHERE asi.M_AttributeSetInstance_ID=p_M_AttributeSetInstance_ID;
        --
        IF (v_SerNo IS NOT NULL) THEN
            v_NameAdd := v_NameAdd || v_SerNoStart || v_SerNo || v_SerNoEnd || ' ';
        END IF;
        IF (v_Lot IS NOT NULL) THEN
            v_NameAdd := v_NameAdd || v_LotStart || v_Lot || v_LotEnd || ' ';
        END IF;
        IF (v_GuaranteeDate IS NOT NULL) THEN
            v_NameAdd := v_NameAdd || CAST(v_GuaranteeDate AS DATE) || ' ';
        END IF;
        --
        
        FOR r IN
	     SELECT ai.Value, a.Name
	        FROM M_AttributeInstance ai
	        INNER JOIN M_Attribute a ON (ai.M_Attribute_ID=a.M_Attribute_ID AND a.IsInstanceAttribute='Y')
        	WHERE ai.M_AttributeSetInstance_ID=p_M_AttributeSetInstance_ID
    	LOOP
            v_NameAdd := v_NameAdd || r.Name || ':' || r.Value || ' ';
        END LOOP;
        --
        IF (LENGTH(v_NameAdd) > 0) THEN
            v_Name := v_Name || ' (' || TRIM(v_NameAdd) || ')';
	ELSE 
	    v_Name := NULL;
        END IF;
    END IF;
    RETURN v_Name;
END;

CONTEXT:  compilation of PL/pgSQL function "productattribute" near line 35
********** Error **********

ERROR: invalid type name "M_AttributeSetInstance.Lot%TYPE"
SQL state: 42601
Context: compilation of PL/pgSQL function "productattribute" near line 35

**Comment by e-Evolution** [comment] 2017-04-15 15:11
Hi Enrique can pelase set of trace error yo know where is call this function fronteras code

**Comment by marcalwestf** [comment] 2017-05-09 16:51
I tried to reproduce the issue by running
_SELECT ProductAttribute (100062) FROM M_InOutLine WHERE M_AttributeSetInstance_ID > 0_
on a databse which contained in _M_InOutLine_ entries  _M_AttributeSetInstance_ID_ >=0  (in this case there was a _M_InOutline_ with the _ASI ID_=100062) .

The result: I got no error. 
It would be useful to get a reproducible configuration.

**Comment by yamelsenih** [comment] 2017-06-18 15:53
Hi @iscapnet it declaration is use on postgreSQl and oracle, i test it function and worked, also i try create other function using a variable with data type like the follow syntax and it is ok:

<pre>
v_Lot           M_AttributeSetInstance.Lot%TYPE;
</pre> 

It only make a variable with the same type of **M_AttributeSetInstance.Lot**

I will to close it issue, if you have more information please write it here for next references

**Closed by yamelsenih** 2017-06-18 15:53 UTC
Labels: (MM) Material Management, 02 bug, 10 Reviewed by Peer, 11 Waiting for Closing

**Comment by klstwh** [comment] 2018-05-02 08:51
I have the same problem:
select adempiere.productattribute(null)
gives:
FEHLER:  ungültiger Typname: »M_AttributeSetInstance.Lot%TYPE«
LINE 35:     v_Lot           M_AttributeSetInstance.Lot%TYPE;

Impact: Material Recipes have empty product name, because in adempiere.m_inout_line_vt
(COALESCE(pt.name, p.name)::text || adempiere.productattribute(iol.m_attributesetinstance_id)::text
the function aborts and the result is null (p.name has content).

**Comment by yamelsenih** [comment] 2018-05-02 14:49
Hi @klstwh what is your PostgreSQL version?

Best Regard

**Comment by klstwh** [comment] 2018-05-07 11:31
Postgres 10.3, no lots etc. defined
