### ISSUE TITLE
Add Payroll Process Report Template

### ISSUE THREAD

**Issue by yamelsenih** [adempiere/adempiere#1558] opened 2018-01-31 18:15 UTC
Is nice to have many templates by process report. With it functionality you can have a payroll process report for show something concepts and it can be showed as:

Portrait
Landscape
Legal
Summary
Detail

**Comment by elmoyses** [comment] 2018-02-09 17:09
The migration script can not be applied. It shows the following errors:
3700

Step 710 Application failed: org.adempiere.exceptions.AdempiereException: SaveError

Step 730 Application failed: org.adempiere.exceptions.AdempiereException: Migration 3700 - Add Payroll Process Report Template #1558 - 3.9.1 (D) ; Step: 730; Type: AD. Step 730, Record 56254 was not found in table Process Parameter (285)

Step 770 Application failed: org.adempiere.exceptions.AdempiereException: Migration 3700 - Add Payroll Process Report Template #1558 - 3.9.1 (D) ; Step: 770; Type: AD. Step 770, Record 56254 was not found in table Process Parameter (285).

**Comment by e-Evolution** [comment] 2018-02-09 19:47
I can replicate the issue

13:43:38.141     PgConnection.setTransactionIsolation:   setTransactionIsolation = {0} (READ COMMITTED) [203]
===========> MigrationFromXML.process: Loading Migration from XML failed. [203]
org.adempiere.exceptions.AdempiereException: Loading migration from /Users/e-Evolution/Develop/ADempiere/adempiere/migration/390lts-391/03700_1558_Add_PayrollReportTemplate.xml failed.
	at org.compiere.process.MigrationFromXML.lambda$loadFile$0(MigrationFromXML.java:168)
	at org.compiere.util.Trx.run(Trx.java:527)
	at org.compiere.util.Trx.run(Trx.java:495)
	at org.compiere.process.MigrationFromXML.loadFile(MigrationFromXML.java:141)
	at org.compiere.process.MigrationFromXML.loadXML(MigrationFromXML.java:107)
	at org.compiere.process.MigrationFromXML.doIt(MigrationFromXML.java:49)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:174)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:127)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:160)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:105)
	at org.compiere.apps.ProcessCtl.startProcess(ProcessCtl.java:623)
	at org.compiere.apps.ProcessCtl.run(ProcessCtl.java:372)
caused by: org.adempiere.exceptions.AdempiereException: Process failed during execution Error:  Migration 3700 - Add Payroll Process Report Template #1558 - 3.9.1 (D) ; Step: 710; Type: AD. Application failed: org.adempiere.exceptions.AdempiereException: SaveError
	at org.eevolution.service.dsl.ProcessBuilder.execute(ProcessBuilder.java:297)
	at org.compiere.process.MigrationFromXML.applyMigration(MigrationFromXML.java:181)
	at org.compiere.process.MigrationFromXML.lambda$loadFile$0(MigrationFromXML.java:163)
	at org.compiere.util.Trx.run(Trx.java:527)
	at org.compiere.util.Trx.run(Trx.java:495)
	at org.compiere.process.MigrationFromXML.loadFile(MigrationFromXML.java:141)
	at org.compiere.process.MigrationFromXML.loadXML(MigrationFromXML.java:107)
	at org.compiere.process.MigrationFromXML.doIt(MigrationFromXML.java:49)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:174)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:127)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:160)

**Comment by yamelsenih** [comment] 2018-02-14 05:29
Hi @e-Evolution @elmoyses i test it now and result is ok, you can see image with a DB seed 3.9:

![screenshot_20180214_012806](https://user-images.githubusercontent.com/2333092/36189035-539e027c-1126-11e8-88ac-03a13e4ac05c.png)

The error is caused by it:

<pre>
[Fatal Error] 03740_1560_Commission_from_past_months.xml:20:59: The content of elements must consist of well-formed character data or markup.
org.xml.sax.SAXParseException; systemId: file:/opt/Development/workspace/adempiere_380/migration/390lts-391/03740_1560_Commission_from_past_months.xml; lineNumber: 20; columnNumber: 59; The content of elements must consist of well-formed character data or markup.
	at org.apache.xerces.parsers.DOMParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.DocumentBuilderImpl.parse(Unknown Source)
	at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:205)
	at org.compiere.process.MigrationFromXML.loadFile(MigrationFromXML.java:133)
	at org.compiere.process.MigrationFromXML.loadXML(MigrationFromXML.java:107)
	at org.compiere.process.MigrationFromXML.doIt(MigrationFromXML.java:49)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:174)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:127)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:160)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:105)
	at org.compiere.apps.ProcessCtl.startProcess(ProcessCtl.java:623)
	at org.compiere.apps.ProcessCtl.run(ProcessCtl.java:372)
	at java.lang.Thread.run(Thread.java:745)
</pre>

And is other issue: 03740_1560_Commission_from_past_months.xml

Best regard.

**Closed** 2018-07-25 05:33 UTC
Labels: (HRM) Human Resource and Payroll Management, (PF) Report Engine & Print Format, 01 enhancement
