### ISSUE TITLE
Sales: Smartbrowser for "Generate shipment" and "Generate Invoice" based on orderlines

### ISSUE THREAD

**Issue by SusanneCalderon** [adempiere/adempiere#760] opened 2017-02-12 02:40 UTC

**Comment by yamelsenih** [comment] 2017-02-19 00:31
Hi @SusanneCalderon i review it and look some observations:

- The XML 01730_UpdateRVTransaction.xml don't have a rollback for the step 0.
- The XML 01730_UpdateRVTransaction.xml don't have Oracle compatibility.
- Yhe XML 01740_SB_ShipmentCreateFromOrderline.xml don't have rollback for the step 1 and 2.
- Yhe XML 01740_SB_ShipmentCreateFromOrderline.xml don't have Oracle compatibility for the step 1 and 2.
- 01740_SB_ShipmentCreateFromOrderline.xml throw a error on step 30: 
<pre>
1740 - SB_InoutGererateFromOrderLine - null (U) ; Step: 30; Type: AD. Step 30, Record 55694 was not found in table Process Parameter (285).
</pre>

**Comment by e-Evolution** [comment] 2017-03-03 01:54
I got next error when execute of migration step.


19:37:51.263 MigrationApply.addLog: 0 - null - null - Migration 1740 - SB_InoutGererateFromOrderLine - null (D) ; Step: 30; Type: AD. Application failed: org.adempiere.exceptions.AdempiereException: Migration 1740 - SB_InoutGererateFromOrderLine - null (D) ; Step: 30; Type: AD. Step 30, Record 55694 was not found in table Process Parameter (285). [1]
19:37:51.263 MigrationApply.addLog: 0 - null - null - Migration 1740 - SB_InoutGererateFromOrderLine - null (D) ; Step: 30; Type: AD. Application failed: org.adempiere.exceptions.AdempiereException: Migration 1740 - SB_InoutGererateFromOrderLine - null (D) ; Step: 30; Type: AD. Step 30, Record 55694 was not found in table Process Parameter (285). [1]
===========> MigrationApply.process: Migration 1740 - SB_InoutGererateFromOrderLine - null (D) ; Step: 30; Type: AD. Application failed: org.adempiere.exceptions.AdempiereException: Migration 1740 - SB_InoutGererateFromOrderLine - null (D) ; Step: 30; Type: AD. Step 30, Record 55694 was not found in table Process Parameter (285). [1]
org.adempiere.exceptions.AdempiereException: Migration 1740 - SB_InoutGererateFromOrderLine - null (D) ; Step: 30; Type: AD. Application failed: org.adempiere.exceptions.AdempiereException: Migration 1740 - SB_InoutGererateFromOrderLine - null (D) ; Step: 30; Type: AD. Step 30, Record 55694 was not found in table Process Parameter (285).
        at org.compiere.model.MMigration.apply(MMigration.java:172)
        at org.compiere.model.MMigration.apply(MMigration.java:170)
        at org.compiere.process.MigrationApply.doIt(MigrationApply.java:53)
        at org.compiere.process.SvrProcess.process(SvrProcess.java:171)
        at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:124)
        at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:160)
        at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:105)
        at org.compiere.process.ServerProcessCtl.startProcess(ServerProcessCtl.java:415)
        at org.compiere.process.ServerProcessCtl.run(ServerProcessCtl.java:246)
        at org.eevolution.service.dsl.ProcessBuilder.run(ProcessBuilder.java:208)
        at org.eevolution.service.dsl.ProcessBuilder.access$200(ProcessBuilder.java:53)
        at org.eevolution.service.dsl.ProcessBuilder$1.run(ProcessBuilder.java:281)
        at org.compiere.util.Trx.run(Trx.java:527)
        at org.eevolution.service.dsl.ProcessBuilder.execute(ProcessBuilder.java:278)
        at org.compiere.process.MigrationFromXML.applyMigration(MigrationFromXML.java:181)
        at org.compiere.process.MigrationFromXML.lambda$loadFile$0(MigrationFromXML.java:163)
        at org.compiere.util.Trx.run(Trx.java:527)
        at org.compiere.util.Trx.run(Trx.java:495)
        at org.compiere.process.MigrationFromXML.loadFile(MigrationFromXML.java:141)
        at org.compiere.process.MigrationFromXML.loadXML(MigrationFromXML.java:107)
        at org.compiere.process.MigrationFromXML.doIt(MigrationFromXML.java:49)
        at org.compiere.process.SvrProcess.process(SvrProcess.java:171)
        at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:124)
caused by: org.adempiere.exceptions.AdempiereException: Migration 1740 - SB_InoutGererateFromOrderLine - null (D) ; Step: 30; Type: AD. Application failed: org.adempiere.exceptions.AdempiereException: Migration 1740 - SB_InoutGererateFromOrderLine - null (D) ; Step: 30; Type: AD. Step 30, Record 55694 was not found in table Process Parameter (285).
        at org.compiere.model.MMigrationStep.bailout(MMigrationStep.java:270)
        at org.compiere.model.MMigrationStep.applyPO(MMigrationStep.java:598)
        at org.compiere.model.MMigrationStep.apply(MMigrationStep.java:227)
        at org.compiere.model.MMigration.apply(MMigration.java:151)
        at org.compiere.model.MMigration.apply(MMigration.java:170)
        at org.compiere.process.MigrationApply.doIt(MigrationApply.java:53)
        at org.compiere.process.SvrProcess.process(SvrProcess.java:171)
        at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:124)
        at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:160)
        at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:105)
        at org.compiere.process.ServerProcessCtl.startProcess(ServerProcessCtl.java:415)
        at org.compiere.process.ServerProcessCtl.run(ServerProcessCtl.java:246)
caused by: org.adempiere.exceptions.AdempiereException: Migration 1740 - SB_InoutGererateFromOrderLine - null (D) ; Step: 30; Type: AD. Step 30, Record 55694 was not found in table Process Parameter (285).
        at org.compiere.model.MMigrationStep.bailout(MMigrationStep.java:272)
        at org.compiere.model.MMigrationStep.bailout(MMigrationStep.java:246)
        at org.compiere.model.MMigrationStep.applyPO(MMigrationStep.java:518)
        at org.compiere.model.MMigrationStep.apply(MMigrationStep.java:227)
        at org.compiere.model.MMigration.apply(MMigration.java:151)
        at org.compiere.model.MMigration.apply(MMigration.java:170)
        at org.compiere.process.MigrationApply.doIt(MigrationApply.java:53)
        at org.compiere.process.SvrProcess.process(SvrProcess.java:171)
        at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:124)
        at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:160)
        at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:105)
        at org.compiere.process.ServerProcessCtl.startProcess(ServerProcessCtl.java:415)
        at org.compiere.process.ServerProcessCtl.run(ServerProcessCtl.java:246)

19:37:51.265   MIssue.create: Migration 1740 - SB_InoutGererateFromOrderLine - null (D) ; Step: 30; Type: AD. Application failed

**Comment by e-Evolution** [comment] 2017-05-10 20:33
![captura de pantalla 2017-05-10 a la s 13 30 54](https://cloud.githubusercontent.com/assets/786968/25919923/1a3549fa-3585-11e7-836d-746f33a59518.png)

13:29:08.672           Trx.commit: **** POSave_b6aae0f7-726e-4b1b-8c3a-4f7c9a5c802c [17]
13:29:08.672     PgConnection.setAutoCommit:   setAutoCommit = {0} (true) [17]
13:29:08.672           Trx.close: POSave_b6aae0f7-726e-4b1b-8c3a-4f7c9a5c802c [17]
===========> ModelValidationEngine.lambda$fireDocValidate$11: org.postgresql.util.PSQLException: ERROR: column "user3_id" does not exist
13:29:08.673         QueryExecutorImpl.execute:   simple execute, handler={0}, maxRows={1}, fetchSize={2}, flags={3} (org.postgresql.jdbc.PgStatement$StatementResultHandler@15b619bd, 0, 0, 23) [17]
  Position: 783
  Location: File: parse_relation.c, Routine: errorMissingColumn, Line: 3090
13:29:08.673         QueryExecutorImpl.sendParse:  FE=> Parse(stmt=null,query="SET SESSION CHARACTERISTICS AS TRANSACTION ISOLATION LEVEL READ COMMITTED",oids={}) [17]
13:29:08.673         QueryExecutorImpl.sendBind:  FE=> Bind(stmt=null,portal=null) [17]
13:29:08.673         QueryExecutorImpl.sendExecute:  FE=> Execute(portal={0},limit={1}) (null, 1) [17]
13:29:08.673         QueryExecutorImpl.sendSync:  FE=> Sync [17]
  Server SQLState: 42703, SQL=SELECT QtyBatchSize,Planner_ID,CopyFrom,QtyBatchs,Processed,DateConfirm,DateDelivered,DateFinish,DateFinishSchedule,DateOrdered,DatePromised,DateStart,DateStartSchedule,Description,QtyReserved,IsApproved,Lot,M_AttributeSetInstance_ID,OrderType,QtyEntered,AD_OrgTrx_ID,User1_ID,User2_ID,IsPrinted,IsQtyPercentage,IsSOTrx,IsSelected,Line,M_Warehouse_ID,FloatBefored,QtyOrdered,QtyReject,DocAction,DocStatus,FloatAfter,QtyScrap,ScheduleType,SerNo,QtyDelivered,DocumentNo,S_Resource_ID,Posted,PriorityRule,AD_Workflow_ID,PP_Product_BOM_ID,Assay,C_Activity_ID,C_Campaign_ID,C_DocTypeTarget_ID,C_DocType_ID,C_OrderLine_ID,C_Project_ID,C_UOM_ID,M_Product_ID,Yield,C_ProjectPhase_ID,C_ProjectTask_ID,M_Shipper_ID,DeliveryRule,DeliveryViaRule,FreightCostRule,M_FreightCategory_ID,TrackingNo,User3_ID,User4_ID,PP_Order_ID,Created,Processing,CreatedBy,AD_Org_ID,AD_Client_ID,Updated,UpdatedBy,IsActive,ProcessedOn FROM PP_Order WHERE ( C_OrderLine_ID = ?  AND DocStatus IN  (?,?) AND EXISTS (SELECT 1 FROM  PP_Order_BOM  WHERE PP_Order_BOM.PP_Order_ID=PP_Order.PP_Order_ID AND PP_Order_BOM.BOMType =? )) [17]
org.adempiere.exceptions.DBException: org.postgresql.util.PSQLException: ERROR: column "user3_id" does not exist
  Position: 783
  Location: File: parse_relation.c, Routine: errorMissingColumn, Line: 3090
  Server SQLState: 42703, SQL=SELECT QtyBatchSize,Planner_ID,CopyFrom,QtyBatchs,Processed,DateConfirm,DateDelivered,DateFinish,DateFinishSchedule,DateOrdered,DatePromised,DateStart,DateStartSchedule,Description,QtyReserved,IsApproved,Lot,M_AttributeSetInstance_ID,OrderType,QtyEntered,AD_OrgTrx_ID,User1_ID,User2_ID,IsPrinted,IsQtyPercentage,IsSOTrx,IsSelected,Line,M_Warehouse_ID,FloatBefored,QtyOrdered,QtyReject,DocAction,DocStatus,FloatAfter,QtyScrap,ScheduleType,SerNo,QtyDelivered,DocumentNo,S_Resource_ID,Posted,PriorityRule,AD_Workflow_ID,PP_Product_BOM_ID,Assay,C_Activity_ID,C_Campaign_ID,C_DocTypeTarget_ID,C_DocType_ID,C_OrderLine_ID,C_Project_ID,C_UOM_ID,M_Product_ID,Yield,C_ProjectPhase_ID,C_ProjectTask_ID,M_Shipper_ID,DeliveryRule,DeliveryViaRule,FreightCostRule,M_FreightCategory_ID,TrackingNo,User3_ID,User4_ID,PP_Order_ID,Created,Processing,CreatedBy,AD_Org_ID,AD_Client_ID,Updated,UpdatedBy,IsActive,ProcessedOn FROM PP_Order WHERE ( C_OrderLine_ID = ?  AND DocStatus IN  (?,?) AND EXISTS (SELECT 1 FROM  PP_Order_BOM  WHERE PP_Order_BOM.PP_Order_ID=PP_Order.PP_Order_ID AND PP_Order_BOM.BOMType =? ))
	at org.compiere.model.Query.firstOnly(Query.java:352)
	at org.eevolution.model.LiberoValidator.updateMPPOrder(LiberoValidator.java:388)
	at org.eevolution.model.LiberoValidator.docValidate(LiberoValidator.java:251)
	at org.compiere.model.ModelValidationEngine.lambda$fireDocValidate$11(ModelValidationEngine.java:510)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.compiere.model.ModelValidationEngine.fireDocValidate(ModelValidationEngine.java:507)
	at org.compiere.model.ModelValidationEngine.fireDocValidate(ModelValidationEngine.java:454)
	at org.compiere.model.MInOut.completeIt(MInOut.java:1653)
	at org.compiere.process.DocumentEngine.completeIt(DocumentEngine.java:479)
	at org.compiere.process.DocumentEngine.processIt(DocumentEngine.java:296)
	at org.compiere.process.DocumentEngine.processIt(DocumentEngine.java:260)
	at org.compiere.model.MInOut.processIt(MInOut.java:1058)
caused by: org.postgresql.util.PSQLException: ERROR: column "user3_id" does not exist
  Position: 783
  Location: File: parse_relation.c, Routine: errorMissingColumn, Line: 3090
  Server SQLState: 42703; State=42703; ErrorCode=0
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2412)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2125)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:297)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:428)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:354)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:169)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:117)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeQuery(NewProxyPreparedStatement.java:76)
	at sun.reflect.GeneratedMethodAccessor7.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.compiere.db.StatementProxy.invoke(StatementProxy.java:100)
	at com.sun.proxy.$Proxy2.executeQuery(Unknown Source)
	at org.compiere.model.Query.createResultSet(Query.java:758)
	at org.compiere.model.Query.firstOnly(Query.java:339)
	at org.eevolution.model.LiberoValidator.updateMPPOrder(LiberoValidator.java:388)
	at org.eevolution.model.LiberoValidator.docValidate(LiberoValidator.java:251)
	at org.compiere.model.ModelValidationEngine.lambda$fireDocValidate$11(ModelValidationEngine.java:510)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)

13:29:08.673         QueryExecutorImpl.processResults:  <=BE ParseComplete [{0}] (null) [17]
13:29:08.673         QueryExecutorImpl.processResults:  <=BE BindComplete [{0}] (unnamed) [17]

**Comment by yamelsenih** [comment] 2017-06-10 00:16
Hi i test it and worked. Also i add improvements on source code, the chage was registered on #1069

**Closed by yamelsenih** 2017-06-10 00:16 UTC
Labels: (SO) Sales Management, 02 bug, 11 Waiting for Closing
