### ISSUE TITLE
Accounting: Process to close the cost/income accounts at the end of the fiscal year

### ISSUE THREAD

**Issue by SusanneCalderon** [adempiere/adempiere#1554] opened 2018-01-27 18:56 UTC
- This process is used at the end of the financial year to clear all cost and income accounts.
- The destination account is selected as a parameter.
- The process creates a GL Journal Batch with GL Journals for every account with a balance.
- After completing the Journal Batch the balance of all income/cost accounts is zero, the transferred amount corresponds to the gross revenue.

**Comment by adaxa-steven** [comment] 2018-01-27 19:15
Hi Susanne,
If you do this and then print a P&L with prior year as comparatives what will be printed?
If you have two accounting schemas one in local currency with 30 June year end and one in Usd with 31 Dec year end what will the Usd P&L look like?

As the financial report writer "knows" that the P&L account balance is zero at the start of the year what is gained by zeroing out each account rather than, say, just posting a 2 line journal that debits a P&L transfer account and credits retained earnings?
Having the process there does not mean it has to be used...  Just interested in why it is needed.
Regards

**Comment by e-Evolution** [comment] 2018-01-28 00:38
@SusanneCalderon 

This a bad practice of traditional box  accounting software and is a request  of latinomerican accountant because not know the concept of perpetual accounting.

http://wiki.adempiere.net/Perpetual_Accounting 

Adempiere not need use a Process to close the cost/income accounts at the end of the fiscal year.

The reason is that accounting engine are based in perpetual accounting and the financial report made the work for you when define a column that calculate  P&L , So you not need set in zero all income and expense account.

So the P&L can be to calculate on the flight and if have any adjustment or modificaction you do not need to do anything.

On the other hand if you use a journal to seting zero when try get the income statement the last period the report only show zero amount that is totalitly incorrect.

I think if a customer ask for this functionality should be  a customization but not should into the Adempiere core functionality because is promote the bad practice or something for which it is not designed

**Comment by SusanneCalderon** [comment] 2018-01-28 02:04
Hi Steven, this process is required in some countries, where a formal year-end closing is needed. This is a fiscal requirement.

In such cases you need the application of the gross revenue, from this amount you start the calculation of the taxes. 

In cases the financial system does not require this formal closing, it can be handeled as you explained it.

**Comment by SusanneCalderon** [comment] 2018-01-28 02:07
@e-Evolution 
This is not a bad practice, it is a fical requirement in some countries. You must abide to it, wheather you like it or not.

**Comment by SusanneCalderon** [comment] 2018-01-28 02:21
Process:
![20180127_year-endclosing_01](https://user-images.githubusercontent.com/15349639/35478316-561f8212-039f-11e8-821f-b847fb2276b1.PNG)

Result:
![20180127_year-endclosing_02](https://user-images.githubusercontent.com/15349639/35478324-980bc802-039f-11e8-909d-26af4a6af50c.PNG)
![20180127_year-endclosing_03](https://user-images.githubusercontent.com/15349639/35478325-9827c1a6-039f-11e8-85a5-5d904f68b359.PNG)
![20180127_year-endclosing_04](https://user-images.githubusercontent.com/15349639/35478326-983e2bbc-039f-11e8-9b95-e3867c4acd6c.PNG)
![20180127_year-endclosing_05](https://user-images.githubusercontent.com/15349639/35478327-985609f8-039f-11e8-8d2d-acfaa3b70e0f.PNG)

**Comment by e-Evolution** [comment] 2018-01-28 04:08
An additional problem to apply its approach is that is necessary   setting all accounts as no  documents controlled, which implies a great risk since the any can register any entries to accounts that should only be apply by the system.

**Comment by adaxa-steven** [comment] 2018-01-28 04:16
You may want to pick up a small adaxa change. On journal document type record an "override doc control" flag is added. Was added to simplify adding opening balances but would work for this also.

**Comment by SusanneCalderon** [comment] 2018-01-31 16:23
@adaxa-steven 
We put the flag in GL_JournalBatch, called isYearEndClosing. But I agree that it is better, to place it in the document type. You need this flag also for the process _Invoice Not Realized Gain/Loss_

**Comment by e-Evolution** [comment] 2018-02-09 19:33
Error in the migration script not can be apply , related issue report #1570

13:22:13.157     PgConnection.setAutoCommit:   setAutoCommit = {0} (false) [150]
13:22:13.157     PgConnection.setTransactionIsolation:   setTransactionIsolation = {0} (READ COMMITTED) [150]
===========> MigrationFromXML.process: Loading Migration from XML failed. [150]
org.adempiere.exceptions.AdempiereException: Loading migration from /Users/e-Evolution/Develop/ADempiere/adempiere/migration/390lts-391/03670_1554_Year-end_Closing.xml failed.
	at org.compiere.process.MigrationFromXML.lambda$loadFile$0(MigrationFromXML.java:168)
	at org.compiere.util.Trx.run(Trx.java:527)
	at org.compiere.util.Trx.run(Trx.java:495)
	at org.compiere.process.MigrationFromXML.loadFile(MigrationFromXML.java:141)
	at org.compiere.process.MigrationFromXML.loadXML(MigrationFromXML.java:107)
	at org.compiere.process.MigrationFromXML.doIt(MigrationFromXML.java:49)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:174)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:127)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:160)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:105)
	at org.compiere.apps.ProcessCtl.startProcess(ProcessCtl.java:623)
	at org.compiere.apps.ProcessCtl.run(ProcessCtl.java:372)
caused by: org.adempiere.exceptions.AdempiereException: Process failed during execution Error:  Migration 3670 - YearEndClosing - 3.9.1 (D) ; Step: 410; Type: AD. Application failed: org.adempiere.exceptions.AdempiereException: Migration 3670 - YearEndClosing - 3.9.1 (D) ; Step: 410; Type: AD. Step 410, Record 54254 was not found in table Tree Node MM (452).
	at org.eevolution.service.dsl.ProcessBuilder.execute(ProcessBuilder.java:297)
	at org.compiere.process.MigrationFromXML.applyMigration(MigrationFromXML.java:181)
	at org.compiere.process.MigrationFromXML.lambda$loadFile$0(MigrationFromXML.java:163)
	at org.compiere.util.Trx.run(Trx.java:527)
	at org.compiere.util.Trx.run(Trx.java:495)
	at org.compiere.process.MigrationFromXML.loadFile(MigrationFromXML.java:141)
	at org.compiere.process.MigrationFromXML.loadXML(MigrationFromXML.java:107)
	at org.compiere.process.MigrationFromXML.doIt(MigrationFromXML.java:49)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:174)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:127)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:160)

**Comment by iscapnet** [comment] 2018-05-13 17:45
Hi, I am wondering if it's possible to allow those year end entries on an adjustment period, say period No. 13. I created this as "adjustment period"  type from Dec-31-2017  to Dec-31-2017, however it doesn't allow to complete this manual Journal. 

The reason I am trying to do this, is because I think if we enter Year End Journal on a separate "adjustment period" we could still leverage financial report capabilities when using historic data... Do you think this would be the right approach?

**Closed** 2019-01-01 23:00 UTC
Labels: (PA) Performance Analysis and General Ledger, 01 enhancement, 04 invalid
