### ISSUE TITLE
Create new design for look and feel style to ADempiere 390

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#1041] opened 2017-05-19 17:22 UTC
Creante new design for look and feel style to ADempiere 390

**Comment by adaxa-steven** [comment] 2017-05-20 05:23
Hi Victor,
I have not seen any information about a new look and feel.
Is there any documentation on it?
Has the community reviewed it?
regards
Steven

**Comment by eduardolopezuy** [comment] 2017-05-22 14:21
Hi Steven,
A working group was first formed months ago  to discuss new MKT actions and the need to give a new face, was understood and for this it was necessary to change the ADempiere logo.
For this, we were helped by Camilo Alvarez, MKT digital specialist, who works at OS Group in Colombia.
This group is working on a new design of the Logo of ADempiere, once it finish will propose the pre-selected options to the community.

Logo
The choosen colors were:
Skyblue: 009bde
Blue: 003764

New logo target:
New colors
Remove Draw ball
Remove icon

ZK User Inteface 
The idea is to modernize the appearance of the UI AD 390, and within our limitations, making it more similar to the main players of the world ERP.
Quickbooks, Infor, Netsuite

Target:
Flat
Minimalist
Header blue. skyblue drops
2 Greys

Change letter to make it readable
Change black letters to gray
Eliminate Degradé from everywhere
Eliminate double headers of blue
Shrink strap logo
Eliminate blue celds lines
More readable icons, new icons
Grids: gray and white alternating in rows
Change colors in login portal


The result of the new logo and the new UI, will be proposed to the community for its comments, as soon as it is finished. We are still working on it.
Anyway, who wants to know about the progress, join this link.
http://190.64.150.102:8273/webui/
GardenAdmin
GardenAdmin

And also who wants to help, is welcome.

**Comment by adaxa-steven** [comment] 2017-05-22 14:49
Hi Eduardo,
I think it looks much better than before :-)
Some comments...
.. for my old eyes there is not enough contrast/colour in the toolbar icons and I find them hard to read.
.. particularly the 'save' button does not "light up" enough and I miss it.

In the Sales Order window the "Target Document Type has a fine dark border (same for all dropdowns) but text Fields like Description have no border. Is that as designed?
![image](https://cloud.githubusercontent.com/assets/15791084/26314540/a8663858-3f51-11e7-88c6-6a19d31406c4.png)

Will HTML reports use the same colours?  Reports don't seem to be working in the test instance so I could not check.

I look forward to seeing the final version of the theme ... do you plan to apply to 390 or later .. because if it is 390 that does not leave much time for the community to review it the final version.

I also note that the 'tab placement' left or right is ignored but presume that is nothing to do with the theme.

regards...

**Comment by eduardolopezuy** [comment] 2017-05-22 15:08
Hi Steven,
Thank you for your comments. All eyes are welcome.
There are a lot of changes to make. Many have already done them, but many more we must do them still.
Icons should be changed, for the reason you said. We have not finished it.
We have seen that many current ERPs have no limits in some texts, which are activated when it is positioned there. We are still testing this. Although I think we should put a gray limit.
I appreciate you putting us here, every detail you find.
But some questions:
What do you think of the color blue?
What do you think of the color combination with the skyblue drops, so that it gives little color to the UI?
Would you like more skyblue?
All your comments help us!
Thank you

**Comment by eduardolopezuy** [comment] 2017-05-22 15:24
The interface change intention is can be integrated as soon as possible, but we are not sure that we will integrate it in 3.90.
The main problem is MKT decisions, color combination, new logos. Not so much to modify the ZK !!
We are a community and we have many members with opinions.
That is why it is best to go slowly agreeing on the changes, because the change we need to make at the moment is very big.

The logo that is winning until this moment is:

![trapecio 3a](https://cloud.githubusercontent.com/assets/13646479/26316056/682d5fe0-3ee9-11e7-9709-186b796db704.jpg)

What is your comments?

**Comment by yamelsenih** [comment] 2017-05-22 15:48
Hi @eduardolopezuy the **A** should be symmetrical with background diagonal.

**Comment by eduardolopezuy** [comment] 2017-05-22 15:59
Hi Yamel,
Yes, you're right Yamel.
That detail is already arranged in the original.
This image is just a sketch.

**Comment by PraponAdempiere** [comment] 2017-05-23 06:10
Which will make a lot of customers?  :)

**Comment by adaxa-steven** [comment] 2017-05-23 06:20
Can these two button sets be merged?
![image](https://cloud.githubusercontent.com/assets/15791084/26340715/3a15cca6-3fd3-11e7-9a24-c1183ac020bd.png)

you could get rid of the green movement buttons by just including them with the page movement buttons at the bottom

||<<   Top     |< page-up   < Line-up   ... then equivalent for moving down 
... using sensible icons of course.
regards

**Comment by jkinfotech** [comment] 2017-05-24 11:11
Hi,

We had modified Adempiere look, Can we go for it. 

This look is as same as @eduardolopezuy is using, But we used some colors for this also and increased font size for few. We also change the menu structure as per our customer demand.

![image](https://cloud.githubusercontent.com/assets/375588/26400548/11a5572e-409f-11e7-8d49-db732d5884b1.png)

**Comment by eduardolopezuy** [comment] 2017-05-26 21:28
![grilla ad](https://cloud.githubusercontent.com/assets/13646479/26513274/fe83279a-4240-11e7-878e-b2252665c2bf.jpg)

**Comment by eduardolopezuy** [comment] 2017-05-26 21:28
![ad nuevo](https://cloud.githubusercontent.com/assets/13646479/26513295/1f04e666-4241-11e7-9423-8b8eab7dfcc1.jpg)

**Comment by eduardolopezuy** [comment] 2017-05-26 21:31
Still have to modify 3 icons.
Who wants to know about the progress, join this link.
http://190.64.150.102:8273/webui/
GardenAdmin
GardenAdmin

**Comment by e-Evolution** [comment] 2017-05-26 22:06
Hi @eduardolopezuy  Eduardo.

Please review this other icons option , I think that icons in blue can have a best integration.

here a good options 

https://www.uxpin.com/uxpin-icon-set.html
https://www.1001freedownloads.com/free-vector/lynny-icons-full

If we want a  complete flat design and nice color, we would use :

https://dribbble.com/shots/1054478-Free-Flat-Icons
https://github.com/icons8/flat-color-icons

Or if we want use flat icons with a good design we would to use the google free icon in in gray 

http://google.github.io/material-design-icons/

only some of my sugesttions.

About the menu selector I think that is a best contrast use blue with white fonts , because use 2 dark color not is good selection.

I think that the new ADempiere icons should to have greater prominence, so that  the top section should be white.

On the other hand here some good recommendation for flat design , for buttons , and dialog icons , calendar  , etc

http://designmodo.github.io/Flat-UI/

kind regards
Victor

**Comment by yamelsenih** [comment] 2017-05-27 01:10
![arbol_32](https://cloud.githubusercontent.com/assets/2333092/26516611/3da01fbc-4257-11e7-858e-6db05f828e8d.png)
Hi @eduardolopezuy thank you for it initiative, my suggestion:

- Red color: the icons is good if are more lives.
- Blue color: is good if all icons are symmetrics.
- Green color: is better if the elements are more visible, also if exists a different colors for enabled value and disabled.

Best regard

**Comment by e-Evolution** [comment] 2017-05-27 01:26
@yamelsenih you are in rightly I try compare a purchase order not completed of purchase order processed or complete , not exist different in in previews look and feel we have.

**Comment by liosc** [comment] 2017-05-27 06:57
Hi everybody and thanks for the good work done. I like the new logo. I like the new look, it is more clean, I would keep going to have an even cleaner effect.
Some suggestions:
- The login page from the link appears with an image in the old style, I think it could be better to have also here the exact new logo.
- I think the background under some titles (RGB[0 143 211]) and buttons (RGB[31 155 222]) could be improved. They don't have a great contrast neither with white nor black. It could be better, for example, the blue activated by hovering (RGB[10 58 94]). It has a nice contrast with white background and it could be better also the contrast with white text and icon on the button (using bright colors).
- The blue bar on top in my opinion should be thinner.

**Comment by sajeevsahadev** [comment] 2017-05-27 11:59
Hi Team, rather than the gitter screen shots, the test server application is giving good UI experience. Few suggestions from my side. 
1. regarding a border for the tool box. Also if the tool box is little projected than the data entry screen, it will be easily noticeable for the users to perform some action.
![image](https://cloud.githubusercontent.com/assets/6624739/26521023/8ab8781a-42ef-11e7-98ab-87b8cb7f71a8.png)

2. The border box of date fields and the other fields are little different. The date fields have little bold border and the other field's border is lite. We can keep uniformity over here.
![image](https://cloud.githubusercontent.com/assets/6624739/26521074/99a33bde-42f0-11e7-9e5e-60e231fdfe92.png)

3. Our fonts are too small to read.
![image](https://cloud.githubusercontent.com/assets/6624739/26521103/31d5e988-42f1-11e7-8702-838bc57e8499.png)

4. The active fields and read only fields are less different in its colors. For showing the ReadOnly, can it be more light blue or a different color itself(may be Gray). 
![image](https://cloud.githubusercontent.com/assets/6624739/26521131/0bbda1fe-42f2-11e7-8c3f-c8e2c813e843.png)

5. Our LEFT alignment Tabs need little more space. 
![image](https://cloud.githubusercontent.com/assets/6624739/26521209/ebcafe76-42f3-11e7-9e0d-7434d9f08a54.png)

I'm not a UI exert, I thought I would share few end user comments.

**Comment by e-Evolution** [comment] 2017-05-27 20:02
Other suggestion that found here:

Change the gradient image to get total flat design

![i372 pimgpsh_fullsize_distr](https://cloud.githubusercontent.com/assets/786968/26524031/6b5bcd30-42ec-11e7-884c-9f30ec93ce06.png)

also the some image for components for combo box  , box date and top column image

![i374 pimgpsh_fullsize_distr](https://cloud.githubusercontent.com/assets/786968/26524044/baa90268-42ec-11e7-9282-09a27b295565.png)

![i379 pimgpsh_fullsize_distr](https://cloud.githubusercontent.com/assets/786968/26524070/66ec70dc-42ed-11e7-8d80-2d63df9c8eda.png)


On the other hand , before existed a orange vertical line that indicate the user that panel master or detail is active , it was change to gray and now not is clear , My suggestion is change to blue vs current gray 

![i375 pimgpsh_fullsize_distr](https://cloud.githubusercontent.com/assets/786968/26524057/19615c88-42ed-11e7-93fb-4d199055cdc6.png)

about the selection menu , I think that should be change blue with white fonts

![i376 pimgpsh_fullsize_distr](https://cloud.githubusercontent.com/assets/786968/26524065/3bf6f884-42ed-11e7-93ef-25f8e93452a5.png)

Because two dark color no show good

in the dialog box , I can see two different blue color and no is nice.

![i380 pimgpsh_fullsize_distr](https://cloud.githubusercontent.com/assets/786968/26524079/8b04ea62-42ed-11e7-8c85-be753b9b5d05.png)

**Comment by ayazbaloch** [comment] 2017-05-28 08:28
Hi all,

I am glade to change new look and feel, there are some tool-tips which still pending to be aligned.
like toggle button and history button tool-tips, see in image.

![image](https://cloud.githubusercontent.com/assets/10656336/26527243/27cb7402-43d3-11e7-8d67-91cd0260b474.png)

And,

![image](https://cloud.githubusercontent.com/assets/10656336/26527263/74dcd4de-43d3-11e7-8a4d-ff157fc075a9.png)

**Comment by eduardolopezuy** [comment] 2017-05-29 14:44
Hi all,
Thanks for all the comments.
We continue working on the new UI, to make a ADempiere more nice and modern !!
We will evaluate all the suggestions that have been made.
At this time we are changing the icons and several small changes.

**Comment by eduardolopezuy** [comment] 2017-05-29 20:40
Many changes were made today.

Still missing:
The font
Some icons sky blue
Align logo

Every time we are closer to achieve it!

Comments are welcome

**Comment by eduardolopezuy** [comment] 2017-05-30 20:36
![login](https://cloud.githubusercontent.com/assets/13646479/26603782/71b136ba-455e-11e7-812d-ddc80f44c68b.jpg)

**Comment by eduardolopezuy** [comment] 2017-05-30 20:36
![1](https://cloud.githubusercontent.com/assets/13646479/26603808/8cc974b2-455e-11e7-96c1-833593da7e41.jpg)

**Comment by eduardolopezuy** [comment] 2017-05-30 20:37
![2](https://cloud.githubusercontent.com/assets/13646479/26603827/97d592e6-455e-11e7-8d66-bc255e937dbc.jpg)

**Comment by eduardolopezuy** [comment] 2017-05-30 20:38
![3](https://cloud.githubusercontent.com/assets/13646479/26603866/bd09fa20-455e-11e7-929a-2b9484f07e65.jpg)

**Comment by eduardolopezuy** [comment] 2017-05-30 20:42
Hi all,
Please enter the same link to browse for yourself.
We are waiting for your comments.

**Comment by yamelsenih** [comment] 2017-05-30 21:26
Hi @eduardolopezuy the follow is my comments:

- The Search window is nice to have the same color for border.

![arbol_33](https://cloud.githubusercontent.com/assets/2333092/26604519/a04d302e-4558-11e7-9742-f8b4560ef8f9.png)

- The tool bar is not homogeneous:
  - Blue: New, minimalist.
  - Red: Old, distinct. Is good if the border on icons are the same.
![arbol_34](https://cloud.githubusercontent.com/assets/2333092/26604931/fa4bc076-4559-11e7-88d4-da602773d9ea.png)

- Lookup element: The combo box item color is not the same, is old color.

![arbol_35](https://cloud.githubusercontent.com/assets/2333092/26605060/85894d34-455a-11e7-9aa5-263d9c5590bc.png)

- Process Parameter: The left button don't have the same background that right button

![arbol_39](https://cloud.githubusercontent.com/assets/2333092/26605091/aaf3ba8c-455a-11e7-83e9-abb55113ead4.png)

- Smart Browse: 
  - The top buttons don't have the same background that action buttons (It is because is disabled?).
  - The lookup for **quantity** don't have the same background that **amount** lookup (It is because is disabled?).

![arbol_40](https://cloud.githubusercontent.com/assets/2333092/26605230/3daae544-455b-11e7-9277-7ff44a714eca.png)

- Table: the selected color dis the old.
![arbol_41](https://cloud.githubusercontent.com/assets/2333092/26605287/6c9103a2-455b-11e7-8fc7-3dcbbc409198.png)

- Main menu: The icons for window, process, report, form, smart browse and other should be more explicit, it help to user to identify each tool.
![arbol_37](https://cloud.githubusercontent.com/assets/2333092/26605419/e950ca94-455b-11e7-8093-04dc712c412c.png)

- The option pane image don't have the new images
![arbol_42](https://cloud.githubusercontent.com/assets/2333092/26605583/9efeeaa6-455c-11e7-8a2a-f95c04a3165d.png)


- **Some observations:**
  - I think that is good define the disable color and it should be very distinct.
  - Is nice to have the new style applied to lookups like: 
    - Combo box.
    - Tables.
    - Calendar
  - Is nice to have a new interface for main page 
![arbol_43](https://cloud.githubusercontent.com/assets/2333092/26605680/f0343d04-455c-11e7-8146-fbb9027f838c.png)

Thank you.
Best regards.

**Comment by eduardolopezuy** [comment] 2017-05-31 14:19
Hi @yamelsenih , please clean your cache and look again.
Several of the observations you make are already made.

**Comment by jdaison** [comment] 2017-05-31 14:33
Hi, I agree with Yamel to review and change icons of menu. They should be similar to the new toolbar icons.
When field is only read need other background to identify easily this difference.

**Comment by jdaison** [comment] 2017-05-31 14:38
![image](https://cloud.githubusercontent.com/assets/6097506/26637357/e4cb9bdc-45e4-11e7-81e0-9ebde10143b7.png)

**Comment by jdaison** [comment] 2017-05-31 14:44
![image](https://cloud.githubusercontent.com/assets/6097506/26637658/b8a3dcd0-45e5-11e7-8b67-0d009d93cc86.png)

**Comment by jdaison** [comment] 2017-05-31 14:57
![image](https://cloud.githubusercontent.com/assets/6097506/26638342/85f7f4cc-45e7-11e7-8315-6f038bc2c75c.png)

**Comment by yamelsenih** [comment] 2017-05-31 23:06
Hi:
The text used for search menu is hide.
![arbol_44](https://cloud.githubusercontent.com/assets/2333092/26657774/f180fd14-4633-11e7-86d0-56b9a36a91fb.png)

Is nice to have more difference between enabled and disabled fields:

- Enabled can be more dark (Label and field).
- Disabled can be more light (Label and field).

![arbol_45](https://cloud.githubusercontent.com/assets/2333092/26657775/f1861fc4-4633-11e7-82e9-95280112884f.png)

**Comment by marcalwestf** [comment] 2017-06-01 00:20
Hi,  here my observations about the new UI in http://190.64.150.102:8273/webui/:

- when a record is edited, I cannot see the _save_ or _undo_ icons highlighted. This is usually a huge help to the users.

- when opening a combo box, the displayed box containing the entries is not indistinctly visible. It should clearly stand out. When the combo box is empty (i.e. there are no entries) it is also difficult to notice it.

- the fields (including combo boxes) which cannot be edited should be painted differently than those which can be edited. In the test url all fields are depicted always the same way. I think here Swing is a good example to follow.

**Comment by adaxa-steven** [comment] 2017-06-01 01:54
Hi
there is nothing to indicate that you can left-mouse-click on the field name and zoom to the underlying record. Underlining of the label to indicate that it is a link would be helpful.
![image](https://cloud.githubusercontent.com/assets/15791084/26661427/f34e15ea-46c0-11e7-92d2-1f37e988f44a.png)

**Comment by adaxa-steven** [comment] 2017-06-01 01:56
the icon for window and report are so similar that user does not understand
![image](https://cloud.githubusercontent.com/assets/15791084/26661491/6053f704-46c1-11e7-851b-70404d7286cd.png)

**Comment by adaxa-steven** [comment] 2017-06-01 02:04
the 'new record' uses black text on blue background that is not readable.  the bottom of the icon is cut off.
![image](https://cloud.githubusercontent.com/assets/15791084/26661677/747a2806-46c2-11e7-8290-9ac511de5405.png)

**Comment by adaxa-steven** [comment] 2017-06-01 02:29
some fields are slightly wider than others causing uneven right border ... could look nicer if lined up.
date fields are one width and number fields a different width ... they could be the same.

![image](https://cloud.githubusercontent.com/assets/15791084/26662237/d7fc76a6-46c5-11e7-9b81-10408a670fee.png)

**Comment by adaxa-steven** [comment] 2017-06-01 02:37
Can the cross to close the window tab be bigger .. easier to find with finger or mouse.

![image](https://cloud.githubusercontent.com/assets/15791084/26662360/aa64a726-46c6-11e7-9fa2-086cd2580c56.png)

![image](https://cloud.githubusercontent.com/assets/15791084/26662392/ebcb8da6-46c6-11e7-9534-107798f05ca0.png)

**Comment by ishanuda** [comment] 2017-06-01 03:21
Hi all,
Thank you very much for the hard work and bringing the AD another step forward,
Here are few comments of mine, if that is possible in the current changes,

![ad-new-look-comment](https://cloud.githubusercontent.com/assets/8893919/26663100/26630ec4-46a6-11e7-885a-9d635ec2b883.png)

A. If we can give a flat looking to the tab,
B. if we can give a sharp corner look rather than the rounded corner
C. if the new look check box can be some thin similar to this
D. if the upper tab also can be with the little X rather than the round closing with an appropriate design if possible
E. if these drop down also can be seen like similar to this,
F. In here adding some padding to the beginning and end of the text,

And also if all the dark blue colors in icons and highlighted areas, tabs etc can be like light blue in D section will give a very beauty look and attractive view

and in my opinion it would give the flat looking a great meaning....

Any way thank you very much all for the hard work done here and taking the application another step forward.

**Comment by e-Evolution** [comment] 2017-06-01 08:39
Hi community  

![captura de pantalla 2017-06-01 a la s 03 32 24](https://cloud.githubusercontent.com/assets/786968/26671597/abaff338-467b-11e7-81b6-d59b10f5053c.png)

This is more close with html report 

![captura de pantalla 2017-06-01 a la s 03 35 00](https://cloud.githubusercontent.com/assets/786968/26671606/aef35742-467b-11e7-98b8-bd1ba1d753bd.png)

What do you think ?

**Comment by adaxa-steven** [comment] 2017-06-01 09:56
In html report does a total line appear in darker blue? 
Where can I test? The instance I can access will not create a report.
Thanks

**Comment by eduardolopezuy** [comment] 2017-06-01 13:33
Hi all,

The selection of the brand colors is a complex issue, and that why several people get involved trying to reach the best combination facing the responsibility of the new identity of ADempiere.
In conclusion, we chose modern corporate colors, selecting the same color combination of the new logo of The Linux Foundation, adding 2 shades of gray. Avoiding to enter in a discussion of many hours by the colors.

Blue: # 003764
Sky Blue: # 008FD3

The reasons for this combination of colors were:
- Blue gives confidence, very similar color than Quickbooks
- Sky Blue gives modernity, in small drops, very similar to Infor

This two colors had good compability with each other giving a good interface experience. The addition of a new lighter sky blue is not compatible with the logo skyblue, nor it is aligned with minimalist and flat trends.

In our opinion if we decide to incorporate new shades of colors, they should be incorporated into corporate identity colors olso. In this case, how will the Logo of Adempiere will look like? It will not have a background color?

This is only our humble opinion. we are open to all kind of comments in order to finish this issue.

regards,

**Comment by eduardolopezuy** [comment] 2017-06-01 13:33
![linux foundation](https://cloud.githubusercontent.com/assets/13646479/26682137/cf505640-46b5-11e7-8f53-4b1bcb3a30d6.png)

**Comment by eduardolopezuy** [comment] 2017-06-01 13:34
![2017-06-01](https://cloud.githubusercontent.com/assets/13646479/26682147/d9dc0fe6-46b5-11e7-8c2f-ed2ac8f610f1.png)

**Comment by eduardolopezuy** [comment] 2017-06-01 13:34
![2017-06-01 1](https://cloud.githubusercontent.com/assets/13646479/26682161/e1eb3400-46b5-11e7-8106-02ee3857995d.png)

**Comment by eduardolopezuy** [comment] 2017-06-01 13:38
![2017-06-01 2](https://cloud.githubusercontent.com/assets/13646479/26682301/653187b0-46b6-11e7-9df7-ecff4289291d.png)

**Comment by cro1y** [comment] 2017-06-01 13:41
While I think the colour makes it stand out nicely, I doubt it's intentional that the "private lock" icon is still the old icon.
![image](https://cloud.githubusercontent.com/assets/6086587/26682319/fdc987d6-46d7-11e7-8e2f-efd942898e1c.png)

**Comment by e-Evolution** [comment] 2017-06-01 14:20
Hi @eduardolopezuy. I think we NO NEED COPY to other or nobody, we have here a lot of people that sent your ideas.

So we should be capable to create our color combination, the problem is use a dark blue color is that no see good in a lot of icons, the icons with dark lines and background in dark blue not is good conbination.

**Comment by yamelsenih** [comment] 2017-06-06 21:27
Hi @eduardolopezuy i have other comment, see the image: Red = Old icon
![arbol_65](https://user-images.githubusercontent.com/2333092/26852780-65bd597c-4add-11e7-8117-df7834924099.png)

**Comment by e-Evolution** [comment] 2017-06-06 21:53
![captura de pantalla 2017-06-06 a la s 16 52 38](https://user-images.githubusercontent.com/786968/26853683-98a2a8ce-4ad8-11e7-8eb0-6e8a4a084fef.png)

The icon with dark lines and blue dark no is nice.

**Comment by e-Evolution** [comment] 2017-06-06 22:23
The icons black lines and background black no is nice.

![captura de pantalla 2017-06-06 a la s 17 20 09](https://user-images.githubusercontent.com/786968/26854671-ce7c8272-4adc-11e7-8448-171bc3f4159f.png)

**Comment by e-Evolution** [comment] 2017-06-06 22:32
The icons with background black have not to clarity and sharpness, some found some meaning?

I think that will good use black and white as icons bars.

![captura de pantalla 2017-06-06 a la s 17 27 16](https://user-images.githubusercontent.com/786968/26854938-0d6c49c6-4ade-11e7-99a8-6b03d6a1683d.png)

**Comment by eduardolopezuy** [comment] 2017-06-07 14:16
Hi all,
Thanks for everyone's comments.
We will continue to work on this.

**Comment by eduardolopezuy** [comment] 2017-06-13 14:14
Hi all,
For better administration of this work we will close this issue and we will open separately each of the modifications detected.

**Comment by yamelsenih** [comment] 2017-06-14 14:47
Hi @eduardolopezuy i push a new branch for it feature, it is https://github.com/adempiere/adempiere/tree/feature/add-new-zk-ui

**Closed** 2017-06-19 18:25 UTC
Labels: 06 help wanted
