### ISSUE TITLE
Error in element definition createshipment should be CreateShipment and define the right element description

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#920] opened 2017-03-31 19:55 UTC
Erro introducing #849

**Comment by e-Evolution** [comment] 2017-03-31 19:56
![captura de pantalla 2017-03-31 a la s 13 56 23](https://cloud.githubusercontent.com/assets/786968/24567202/dd3d1e7c-1619-11e7-91dc-317c666e8df3.png)

**Comment by marcalwestf** [comment] 2017-03-31 23:17
this is not a bug. A bug is when the system doesn't work or the functionality is corrupted.

I am going to take care of it.

**Comment by e-Evolution** [comment] 2017-03-31 23:51
But is incorrect how you create of column and element not use the ADempiere Best Practice of element no is documented

**Comment by marcalwestf** [comment] 2017-04-01 00:54
Committed, see https://github.com/adempiere/adempiere/issues/760
Commit https://github.com/adempiere/adempiere/commit/d04b2cff4052f029edd18d54d1f801458739fd91

**Comment by marcalwestf** [comment] 2017-04-01 01:15
Problem is that System Element _createshipment_ has wrong definition (here screeshot from Adempiere 3.8).
 
![20170331_element_01](https://cloud.githubusercontent.com/assets/1789408/24573815/5159c05e-1646-11e7-8ddd-f62c978ca74d.png)
This has to be corrected so it doesn't happen in the future.

**Comment by yamelsenih** [comment] 2017-06-03 01:05
Hi @e-Evolution @marcalwestf , i change it in https://github.com/adempiere/adempiere/commit/7d86424f145e818695f762b54a30d6f830e17894Also add to process parameter de follow:
![arbol_54](https://cloud.githubusercontent.com/assets/2333092/26749332/4e527696-47d6-11e7-83fa-02f5f9340f12.png)

**Closed by yamelsenih** 2017-06-03 01:05 UTC
Labels: 10 Reviewed by Peer, 11 Waiting for Closing
